### ISSUE TITLE
Import, convert, export Config and/or _Config methods.

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy-config#19]
**Description:**

- [x] Discuss naming convention for all the methods related to serializing, exporting, and loading the various _Configs and the Config objects. Done [here](https://docs.google.com/document/d/1vOuXbJKHxvY2Ee2UPkruWgYhVW6YHthbnkqnmuoN4zE/edit#)
- [x] Implement the methods
- [x] Test all methods
- [x] update documentation

**Comment by jrobinAV** [comment]
https://docs.google.com/document/d/1vOuXbJKHxvY2Ee2UPkruWgYhVW6YHthbnkqnmuoN4zE/edit#

**Comment by trgiangdo** [comment]
Hi @joaoandre-avaiga, with the update of this, there are some test failing on taipy-core when using `export` and `load` method.

**Comment by joaoandre-avaiga** [comment]
Hello! Thank you, I will fix it ASAP.
