### ISSUE TITLE
Ignore unnecessary attributes on _ConfigComparator

### ISSUE THREAD

**Issue by trgiangdo** [Avaiga/taipy-config#52]
**Description**

Create API to define unnecessary attributes that can be ignored when comparing the Config between versions on the Version control system.

These include:
- Job execution Configuration
- GUI Configuration

**Comment by jrobinAV** [comment]
I don't understand why you propose ignoring some attributes during the comparison. We do have the --force option to get over the conflicts. What is the problem to solve here ?

**Comment by trgiangdo** [comment]
Since we remove --force from experiment mode, this is to make sure that the user can re-run an experiment version when he/she updates GUI config, or Job config (for now).

Also, this would remove unnecessary warning from the _ConfigComparator as well.

**Comment by jrobinAV** [comment]
OK I get it.

Maybe instead of just ignoring some attributes, we can make them not blocking for running the app. What do you think?
